routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\HomepageController;
            // add routes here

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// add web routes here
Route::view('/', [HomepageController::class , 'homepage']);
Route::view('/admin/{path?}', 'admin');
Route::view('/admin/module/{path?}', 'admin');
Route::view('/admin/{module?}/{task?}', 'admin');

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Backstage</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
        <link href="{{ asset('/admin/lib/font-awesome/css/font-awesome.css')}}" rel="stylesheet">
        <link href="{{ asset('/admin/lib/Ionicons/css/ionicons.css')}}" rel="stylesheet">
        <link href="{{ asset('/admin/lib/perfect-scrollbar/css/perfect-scrollbar.css')}}" rel="stylesheet">
        <link href="{{ asset('/admin/lib/rickshaw/rickshaw.min.css')}}" rel="stylesheet">
        <script src="{{asset('js/app.js')}}" defer></script>
        <link rel="stylesheet" href="{{asset('css/starlight.css')}}">
    </head>
    <body>
        <div id="app"></div>


        </div><!-- sl-mainpanel -->
        <!-- ########## END: MAIN PANEL ########## -->
    <script src="{{ asset('/admin/lib/jquery/jquery.js') }}"></script>
    <script src="{{ asset('/admin/lib/popper.js/popper.js') }}"></script>
    <script src="{{ asset('/admin/lib/jquery-ui/jquery-ui.js') }}"></script>
    <script src="{{ asset('/admin/lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js') }}"></script>
    <script src="{{ asset('/admin/lib/jquery.sparkline.bower/jquery.sparkline.min.js') }}"></script>
    <script src="{{ asset('/admin/lib/d3/d3.js') }}"></script>
    <script src="{{ asset('/admin/lib/rickshaw/rickshaw.min.js') }}"></script>
    <script src="{{ asset('/admin/lib/chart.js/Chart.js') }}"></script>
    <script src="{{ asset('/admin/lib/Flot/jquery.flot.js') }}"></script>
    <script src="{{ asset('/admin/lib/Flot/jquery.flot.pie.js') }}"></script>
    <script src="{{ asset('/admin/lib/Flot/jquery.flot.resize.js') }}"></script>
    <script src="{{ asset('/admin/lib/flot-spline/jquery.flot.spline.js') }}"></script>

    <script src="{{ asset('/admin/js/starlight.js') }}"></script>
    <script src="{{ asset('/admin/js/ResizeSensor.js') }}"></script>
    <script src="{{ asset('/admin/js/dashboard.js') }}"></script>
  </body>
</html>

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Backstage</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{asset('css/starlight.css')}}">
        <script src="{{asset('js/app.js')}}" defer></script>
    </head>
    <body>
        <div id="app"></div>

    </body>
</html>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/root.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Backstage</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{asset('css/starlight.css')}}">
        <script src="{{asset('js/app.js')}}" defer></script>
    </head>
    <body>
        <div id="app"></div>

    </body>
</html>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>